plugins:
  - '@dotcom-tool-kit/component'
  - '@dotcom-tool-kit/mocha'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/husky-npm'
  - '@dotcom-tool-kit/lint-staged-npm'
  - '@dotcom-tool-kit/node'
commands:
  test:local:
    - Eslint
    - Mocha
  test:ci:
    - Eslint
    - Mocha
  git:precommit:
    - LintStaged
options:
  plugins:
    '@dotcom-tool-kit/circleci':
      cimgNodeVersions:
        - '20.18'
        - '18.20'
    '@dotcom-tool-kit/doppler':
      project: repo_n-express
  tasks:
    Mocha:
      files: "test/**/*.test.js"
    Node:
      entry: "test/fixtures/app/main.js"
      useDoppler: false
