plugins:
  - '@dotcom-tool-kit/component'
  - '@dotcom-tool-kit/mocha'
  - '@dotcom-tool-kit/eslint'
  - '@dotcom-tool-kit/husky-npm'
  - '@dotcom-tool-kit/lint-staged-npm'
  - '@dotcom-tool-kit/node'
hooks:
  test:local:
    - Eslint
    - Mocha
  test:ci:
    - Eslint
    - Mocha
  git:precommit:
    - LintStaged
options:
  "@dotcom-tool-kit/mocha":
    files: "test/**/*.test.js"
  "@dotcom-tool-kit/node":
    entry: "test/fixtures/app/main.js"
    useVault: false
  '@dotcom-tool-kit/circleci':
    nodeVersion:
      - '20.11'
      - '18.16'
