sudo: false
language: node_js
node_js:
- 0.12.2
install:
- make install
script:
- make test
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: ccXYzgs2T+t2zW2Mw9Tz9Ivat7DkjAMN3wzYG9/BNEjeAhhnOraE36dDHVO0DgiNC2cJr6OOpnsxRDUc0K6yC6b/C7Ig7RuUq2Xm7hC47x0dohvV9gAmDgYeUTkB0YINMBtVmWhZgJQTS1WbqYpvX73UXtWn/A2oHSlPdQQMejM=
  on:
    tags: true
    repo: Financial-Times/next-express
notifications:
  slack:
    secure: e0SzW26oeX02Eanfiz5aqOjuob5x+55xnj8LSt6g/Xf3uKkSlFwOuvnKfsB9tpRFs86ztKxdgNEuH4k7bM4ICwi4YB64zHA3wQCyG7EidneIlCiDa+fQ1AzjdAeaKwPYBirxxYhHWkbVYf/m70FeRyjwbbwlueabNUjOrB8wUXc=
