sudo: false
language: node_js
node_js:
- 0.12.2
cache:
  directories:
  - node_modules
  - bower_components
install:
- make install
script:
- make test
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: matt@mattandre.ws
  api_key:
    secure: HKBkwMuL34GNKLvvpg9SNMznAvBLBtck/EaYkPjuJ3GpXG3eqy6aXyaxgLx3QcWuxpTC40dIh8kUxtgJRD8H6qgsdjSRsH+i/oTljd0LqrSiDpbrfXYblpWyXed2WYDYFwczYxmp919GTrEGoa9uqAmK5Ug14ZpLtujFHkhUzJ8=
  on:
    all_branches: true
    tags: true
    repo: Financial-Times/next-express
notifications:
  slack:
    secure: e0SzW26oeX02Eanfiz5aqOjuob5x+55xnj8LSt6g/Xf3uKkSlFwOuvnKfsB9tpRFs86ztKxdgNEuH4k7bM4ICwi4YB64zHA3wQCyG7EidneIlCiDa+fQ1AzjdAeaKwPYBirxxYhHWkbVYf/m70FeRyjwbbwlueabNUjOrB8wUXc=
