sudo: false
language: node_js
node_js:
- 0.12.2
install:
- make install
script:
- make test
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: strategic.products@ft.com
  api_key:
    secure: bU9JZeQzEfzHcqJNOjGWaR0Rq7dWTPwwUKoOBzFOQXxaUriLx3KViPgGzHvDx5i3ffDpM43u0TDWqfhhl6j5Ar8dPUFCNPibmQ6J5yo+wUDv13XLwjLriE7yCLxRL2WKdrCUfDUNzd5DGZHiP7TBcFmMGtBEACJQogcMnKuqWuU=
  on:
    tags: true
    repo: Financial-Times/next-express
notifications:
  slack:
    secure: e0SzW26oeX02Eanfiz5aqOjuob5x+55xnj8LSt6g/Xf3uKkSlFwOuvnKfsB9tpRFs86ztKxdgNEuH4k7bM4ICwi4YB64zHA3wQCyG7EidneIlCiDa+fQ1AzjdAeaKwPYBirxxYhHWkbVYf/m70FeRyjwbbwlueabNUjOrB8wUXc=
