sudo: false
language: node_js
node_js:
- 0.12.2
install:
- make install
script:
- make test
before_deploy:
- npm-prepublish --verbose
deploy:
  provider: npm
  email: matt@mattandre.ws
  api_key:
    secure: WS3szo6PlVio3iJH+5WmPSHLOf4uoEiPcKvsWdOurdnq4COAYfhBklNJtzS06RcZdSxd+HKZmcsYGL69xjehp8GtLYIGZg0tns0OOCw+CKhun79dPZbnfaGpsu1WwDFEp2P5LkJfa9bLXSqmupImSpA7Xfi3goxtk4+2y1pZB9E=
  on:
    all_branches: true
    tags: true
    repo: Financial-Times/next-express
notifications:
  slack:
    secure: e0SzW26oeX02Eanfiz5aqOjuob5x+55xnj8LSt6g/Xf3uKkSlFwOuvnKfsB9tpRFs86ztKxdgNEuH4k7bM4ICwi4YB64zHA3wQCyG7EidneIlCiDa+fQ1AzjdAeaKwPYBirxxYhHWkbVYf/m70FeRyjwbbwlueabNUjOrB8wUXc=
